version: "3.8"

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${WP_DB_NAME}
      MYSQL_USER: ${WP_DB_USER}
      MYSQL_PASSWORD: ${WP_DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "127.0.0.1:8888:80"
      - "127.0.0.1:443:443"
    restart: always
    user: "1000:1000"
    environment:
      WORDPRESS_DB_HOST: ${WP_DB_HOST}
      WORDPRESS_DB_NAME: ${WP_DB_NAME}
      WORDPRESS_DB_USER: ${WP_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WP_DB_PASSWORD}
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html/
      - ./config/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:latest
    ports:
      - "127.0.0.1:888:80"
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
volumes:
  db_data: